# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node

name: execute-tests
on: [push, pull_request]
jobs:
  execute-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.16.0
      uses: actions/setup-node@v2
      with:
        node-version: 14.16.0
    - name: Create and populate .env file then deploy app and run tests
      env:
        MONGO_URL: ${{ secrets.MONGO_URL }}
        ID_ORGANIZACION: ${{ secrets.ID_ORGANIZACION }}
        TOKEN_APLICACION: ${{ secrets.TOKEN_APLICACION }}
      run: |
          touch .env
          echo MONGO_URL="$MONGO_URL" >> .env
          echo ID_ORGANIZACION="$ID_ORGANIZACION" >> .env
          echo TOKEN_APLICACION="$TOKEN_APLICACION" >> .env
          npm ci
          npm run ci
      shell: bash
