# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node

name: execute-tests
on: [push]
jobs:
  execute-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.16.0
      uses: actions/setup-node@v2
      with:
        node-version: 14.16.0
    - name: Create and populate .env file then deploy app and run tests
      env:
        MONGO_URL: ${{ secrets.MONGO_URL }}
        ID_ORGANIZACION: ${{ secrets.ID_ORGANIZACION }}
        TOKEN_APLICACION: ${{ secrets.TOKEN_APLICACION }}
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        CHATID: ${{ secrets.CHATID }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_USERBOT: ${{ secrets.TELEGRAM_USERBOT }}
        VUE_APP_FB_API_PAGE_TOKEN: ${{ secrets.VUE_APP_FB_API_PAGE_TOKEN }}
        VUE_APP_FB_GRAPH_VERSION: ${{ secrets.VUE_APP_FB_GRAPH_VERSION }}
        VUE_APP_FB_PAGE_ID: ${{ secrets.VUE_APP_FB_PAGE_ID }}
        VUE_APP_FRONTEND_URL: ${{ secrets.VUE_APP_FRONTEND_URL }}
        VUE_APP_BACKEND_URL: ${{ secrets.VUE_APP_BACKEND_URL }}
        LOGIN_USERNAME: ${{ secrets.LOGIN_USERNAME }}
        LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
      run: |
          touch .env
          echo MONGO_URL="$MONGO_URL" >> .env
          echo ID_ORGANIZACION="$ID_ORGANIZACION" >> .env
          echo TOKEN_APLICACION="$TOKEN_APLICACION" >> .env
          echo TWITTER_API_KEY="$TWITTER_API_KEY" >> .env
          echo TWITTER_API_SECRET="$TWITTER_API_SECRET" >> .env
          echo TWITTER_ACCESS_TOKEN="$TWITTER_ACCESS_TOKEN" >> .env
          echo TWITTER_ACCESS_TOKEN_SECRET="$TWITTER_ACCESS_TOKEN_SECRET" >> .env
          echo CHATID="$CHATID" >> .env
          echo TELEGRAM_TOKEN="$TELEGRAM_TOKEN" >> .env
          echo TELEGRAM_USERBOT="$TELEGRAM_USERBOT" >> .env          
          echo VUE_APP_FB_API_PAGE_TOKEN="$VUE_APP_FB_API_PAGE_TOKEN" >> .env
          echo VUE_APP_FB_GRAPH_VERSION="$VUE_APP_FB_GRAPH_VERSION" >> .env
          echo VUE_APP_FB_PAGE_ID="$VUE_APP_FB_PAGE_ID" >> .env
          echo VUE_APP_FRONTEND_URL="$VUE_APP_FRONTEND_URL" >> .env
          echo VUE_APP_BACKEND_URL="$VUE_APP_BACKEND_URL" >> .env
          echo LOGIN_USERNAME="$LOGIN_USERNAME" >> .env
          echo LOGIN_PASSWORD="$LOGIN_PASSWORD" >> .env
          npm ci
          npm run ci
      shell: bash
